stages:
  - build
  - test
  - deploy

default:
  tags:
    - vm2-shell

build_app:
  stage: build
  script:
    - ./scripts/ci/build.sh
  artifacts:
    paths:
      - artifacts/publish/
    expire_in: 1 day

test_app:
  stage: test
  script:
    - ./scripts/ci/test.sh

deploy_app:
  stage: deploy
  dependencies:
    - build_app
  script:
    - ./scripts/ci/deploy.sh
  environment:
    name: marketstat-vm1
    url: $DEPLOY_PUBLIC_URL
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
      when: manual
      allow_failure: true
    - when: never

notify_pipeline:
  stage: .post
  script:
    - ./scripts/ci/notify.py
  rules:
    - when: always
