using MarketStat.Common.Core.MarketStat.Common.Core.Dimensions;
using MarketStat.Common.Exceptions;
using MarketStat.Database.Core.Repositories.Dimensions;
using MarketStat.Services.Dimensions.DimEmployeeService.Validators;
using Microsoft.Extensions.Logging;

namespace MarketStat.Services.Dimensions.DimEmployeeService;

public class DimEmployeeService : IDimEmployeeService
{
    private readonly IDimEmployeeRepository _dimEmployeeRepository;
    private readonly ILogger<DimEmployeeService> _logger;

    public DimEmployeeService(IDimEmployeeRepository dimEmployeeRepository, ILogger<DimEmployeeService> logger)
    {
        _dimEmployeeRepository = dimEmployeeRepository;
        _logger = logger;
    }
    
    public async Task<DimEmployee> CreateEmployeeAsync(string employeeRefId, DateOnly birthDate, DateOnly careerStartDate, string? gender)
    {
        DimEmployeeValidator.ValidateForCreate(employeeRefId, birthDate, careerStartDate, gender);
        _logger.LogInformation("Service: Attempting to create employee with RefId: {EmployeeRefId}", employeeRefId);

        var employee = new DimEmployee(
            employeeId: 0, // ID will be generated by DB
            employeeRefId: employeeRefId,
            birthDate: birthDate,
            careerStartDate: careerStartDate,
            gender: gender
        );

        try
        {
            await _dimEmployeeRepository.AddEmployeeAsync(employee);
            _logger.LogInformation("Service: Created DimEmployee {EmployeeId} with RefId {EmployeeRefId}", employee.EmployeeId, employee.EmployeeRefId);
            return employee;
        }
        catch (ConflictException ex)
        {
            _logger.LogError(ex, "Service: Conflict creating employee with RefId '{EmployeeRefId}'.", employee.EmployeeRefId);
            throw;
        }
    }
    
    public async Task<DimEmployee> GetEmployeeByIdAsync(int employeeId)
    {
        _logger.LogInformation("Service: Fetching employee by ID: {EmployeeId}", employeeId);
        return await _dimEmployeeRepository.GetEmployeeByIdAsync(employeeId);
    }
    
    public async Task<IEnumerable<DimEmployee>> GetAllEmployeesAsync()
    {
        _logger.LogInformation("Service: Fetching all employees.");
        var list = await _dimEmployeeRepository.GetAllEmployeesAsync();
        _logger.LogInformation("Service: Fetched {Count} employee records", list.Count());
        return list;
    }
    
    public async Task<DimEmployee> UpdateEmployeeAsync(int employeeId, string employeeRefId, DateOnly birthDate, DateOnly careerStartDate, string? gender)
    {
        DimEmployeeValidator.ValidateForUpdate(employeeId, employeeRefId, birthDate, careerStartDate, gender);
        _logger.LogInformation("Service: Attempting to update DimEmployee {EmployeeId}", employeeId);
            
        try
        {
            var existingEmployee = await _dimEmployeeRepository.GetEmployeeByIdAsync(employeeId);
                
            existingEmployee.EmployeeRefId = employeeRefId;
            existingEmployee.BirthDate = birthDate;
            existingEmployee.CareerStartDate = careerStartDate;
            existingEmployee.Gender = gender;
                
            await _dimEmployeeRepository.UpdateEmployeeAsync(existingEmployee);
            _logger.LogInformation("Service: Updated DimEmployee {EmployeeId}", employeeId);
            return existingEmployee;
        }
        catch (NotFoundException ex)
        {
            _logger.LogWarning(ex, "Service: Cannot update employee {EmployeeId}, as it was not found.", employeeId);
            throw;
        }
        catch (ConflictException ex)
        {
            _logger.LogError(ex, "Service: Conflict when updating employee {EmployeeId}.", employeeId);
            throw;
        }
    }
    
    public async Task DeleteEmployeeAsync(int employeeId)
    {
        _logger.LogInformation("Service: Attempting to delete DimEmployee {EmployeeId}", employeeId);
        await _dimEmployeeRepository.DeleteEmployeeAsync(employeeId);
        _logger.LogInformation("Service: Deleted DimEmployee {EmployeeId}", employeeId);
    }
}