-- Script to load generated targeted salary facts into the database
-- This script is intended to be run using psql, e.g.:
-- psql -U marketstat_etl_user -d marketstat -h localhost -f /path/to/this/load_targeted_facts.sql

\echo '--- Starting Load Process for Targeted Salary Facts ---'
\set ON_ERROR_STOP on

SET search_path = marketstat, public;

-- The name of the CSV file generated by your Python script
\set csv_file_path '/home/andres/Desktop/6Semester/SoftwareDesign/PPO/database/targeted_salary_facts_2024_2025.csv'
-- IMPORTANT: Ensure this path is correct and accessible by the psql client.

-- Step 1: Generate the unique part of the table name using a query
SELECT translate(gen_random_uuid()::text, '-', '') AS temp_table_suffix_val \gset
\set source_csv_staging_table 'temp_source_csv_data_' :temp_table_suffix_val

\echo 'Generated temporary staging table name will be: ' :'source_csv_staging_table'

BEGIN; -- Start a transaction

\echo 'Step 2: Creating temporary staging table ' :'source_csv_staging_table' ' for CSV data...'
-- Use direct psql variable interpolation for CREATE TEMP TABLE.
-- The table name generated should be a valid unquoted identifier.
CREATE TEMP TABLE :source_csv_staging_table (
    recorded_date_text TEXT,
    city_name TEXT,
    oblast_name TEXT,
    employer_name TEXT,
    standard_job_role_title TEXT,
    job_role_title TEXT,
    hierarchy_level_name TEXT,
    employee_birth_date_text TEXT,
    employee_career_start_date_text TEXT,
    salary_amount NUMERIC(18,2),
    bonus_amount NUMERIC(18,2)
) ON COMMIT DROP; -- Table will be dropped at the end of the transaction

\echo 'Temporary staging table created: ' :'source_csv_staging_table'

\echo 'Step 3: Copying data from CSV file into staging table...'
\echo 'CSV File Path: ' :'csv_file_path'
-- Corrected \copy command: Use the variable directly without extra quotes.
-- psql will substitute the value of source_csv_staging_table here.
\copy :source_csv_staging_table FROM :'csv_file_path' WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',');

\echo 'Data copied from CSV to staging table ' :'source_csv_staging_table'.'
-- Verify rows copied:
SELECT COUNT(*) AS rows_in_staging FROM :"source_csv_staging_table"; -- Quoting here is for SQL, not psql var

\echo 'Step 4: Calling stored procedure marketstat.bulk_load_salary_facts_from_staging...'
-- Pass the table name as a string literal to the procedure.
CALL marketstat.bulk_load_salary_facts_from_staging(:'source_csv_staging_table');

\echo 'Stored procedure executed.'

-- The temporary staging table :'source_csv_staging_table' will be dropped automatically ON COMMIT.

COMMIT; -- Commit the transaction

\echo '--- Load Process for Targeted Salary Facts Finished ---'
\echo 'Check marketstat.fact_salaries for new records and marketstat.failed_salary_facts_load for any errors.'

