// <auto-generated />
using System;
using MarketStat.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketStat.Database.Context.Migrations
{
    [DbContext(typeof(MarketStatDbContext))]
    partial class MarketStatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("marketstat")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketStat.Common.Core.MarketStat.Common.Core.Facts.FactSalary", b =>
                {
                    b.Property<int>("DateId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalaryAmount")
                        .HasColumnType("numeric");

                    b.Property<long>("SalaryFactId")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("MarketStat.Common.Dto.MarketStat.Common.Dto.Facts.PublicRoleByLocationIndustryDto", b =>
                {
                    b.Property<decimal>("AverageSalary")
                        .HasColumnType("numeric");

                    b.Property<long>("SalaryRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("StandardJobRoleTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("MarketStat.Common.Dto.MarketStat.Common.Dto.Facts.PublicSalaryByEducationInIndustryDto", b =>
                {
                    b.Property<decimal>("AverageSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("EducationLevelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EducationSpecialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployeeCountForLevel")
                        .HasColumnType("bigint");

                    b.Property<long>("OverallSpecialtyEmployeeCount")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("MarketStat.Common.Dto.MarketStat.Common.Dto.Facts.PublicTopEmployerRoleSalariesInIndustryDto", b =>
                {
                    b.Property<decimal>("AverageSalaryForRole")
                        .HasColumnType("numeric");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployerRank")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleRankWithinEmployer")
                        .HasColumnType("bigint");

                    b.Property<long>("SalaryRecordCountForRole")
                        .HasColumnType("bigint");

                    b.Property<string>("StandardJobRoleTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("MarketStat.Common.Dto.MarketStat.Common.Dto.Facts.SalaryDistributionBucketDto", b =>
                {
                    b.Property<long>("BucketCount")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "bucket_count");

                    b.Property<decimal>("LowerBound")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "lower_bound");

                    b.Property<decimal>("UpperBound")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "upper_bound");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("MarketStat.Common.Dto.MarketStat.Common.Dto.Facts.SalarySummaryDto", b =>
                {
                    b.Property<decimal?>("AverageSalary")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "average_salary");

                    b.Property<decimal?>("Percentile25")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "percentile25");

                    b.Property<decimal?>("Percentile50")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "percentile50");

                    b.Property<decimal?>("Percentile75")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "percentile75");

                    b.Property<decimal?>("PercentileTarget")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "percentile_target");

                    b.Property<long>("TotalCount")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "total_count");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("MarketStat.Common.Dto.MarketStat.Common.Dto.Facts.SalaryTimeSeriesPointDto", b =>
                {
                    b.Property<decimal?>("AvgSalary")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "avg_salary");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasAnnotation("Relational:JsonPropertyName", "period_start");

                    b.Property<long>("SalaryCountInPeriod")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "salary_count_in_period");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimDateDbModel", b =>
                {
                    b.Property<int>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("date_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DateId"));

                    b.Property<DateOnly>("FullDate")
                        .HasColumnType("date")
                        .HasColumnName("full_date");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("Quarter")
                        .HasColumnType("integer")
                        .HasColumnName("quarter");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("DateId");

                    b.HasIndex("FullDate")
                        .IsUnique();

                    b.ToTable("dim_date", "marketstat", t =>
                        {
                            t.HasCheckConstraint("CK_dim_date_month", "\"month\" BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_dim_date_quarter", "\"quarter\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimEducationDbModel", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("education_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EducationId"));

                    b.Property<string>("EducationLevelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("education_level_name");

                    b.Property<string>("SpecialtyCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("specialty_code");

                    b.Property<string>("SpecialtyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("specialty_name");

                    b.HasKey("EducationId");

                    b.HasIndex("SpecialtyName", "EducationLevelName")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_education");

                    b.ToTable("dim_education", "marketstat");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimEmployeeDbModel", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateOnly>("CareerStartDate")
                        .HasColumnType("date")
                        .HasColumnName("career_start_date");

                    b.Property<int?>("EducationId")
                        .HasColumnType("integer")
                        .HasColumnName("education_id");

                    b.Property<string>("EmployeeRefId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("employee_ref_id");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender");

                    b.Property<short?>("GraduationYear")
                        .HasColumnType("smallint")
                        .HasColumnName("graduation_year");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EducationId");

                    b.HasIndex("EmployeeRefId")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_employee_ref_id");

                    b.ToTable("dim_employee", "marketstat", t =>
                        {
                            t.HasCheckConstraint("ck_career_after_birth", "\"career_start_date\" > \"birth_date\"");

                            t.HasCheckConstraint("ck_career_min_age", "\"career_start_date\" >= \"birth_date\" + INTERVAL '16 years'");

                            t.HasCheckConstraint("ck_dim_emp_birth_date", "\"birth_date\" <= CURRENT_DATE");

                            t.HasCheckConstraint("ck_dim_emp_career_start", "\"career_start_date\" <= CURRENT_DATE");
                        });
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimEmployerDbModel", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployerId"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("employer_name");

                    b.Property<int>("IndustryFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("industry_field_id");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inn");

                    b.Property<string>("Kpp")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("kpp");

                    b.Property<string>("LegalAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_address");

                    b.Property<string>("Ogrn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("ogrn");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("registration_date");

                    b.HasKey("EmployerId");

                    b.HasIndex("EmployerName")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_employer_name");

                    b.HasIndex("IndustryFieldId");

                    b.HasIndex("Inn")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_employer_inn");

                    b.HasIndex("Ogrn")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_employer_ogrn");

                    b.ToTable("dim_employer", "marketstat");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimIndustryFieldDbModel", b =>
                {
                    b.Property<int>("IndustryFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("industry_field_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IndustryFieldId"));

                    b.Property<string>("IndustryFieldCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("industry_field_code");

                    b.Property<string>("IndustryFieldName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("industry_field_name");

                    b.HasKey("IndustryFieldId");

                    b.HasIndex("IndustryFieldCode")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_industry_field_code");

                    b.HasIndex("IndustryFieldName")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_industry_field_name");

                    b.ToTable("dim_industry_field", "marketstat");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimJobDbModel", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<string>("HierarchyLevelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hierarchy_level_name");

                    b.Property<int>("IndustryFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("industry_field_id");

                    b.Property<string>("JobRoleTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("job_role_title");

                    b.Property<string>("StandardJobRoleTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("standard_job_role_title");

                    b.HasKey("JobId");

                    b.HasIndex("IndustryFieldId");

                    b.HasIndex("JobRoleTitle", "StandardJobRoleTitle", "HierarchyLevelName", "IndustryFieldId")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_job");

                    b.ToTable("dim_job", "marketstat");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimLocationDbModel", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("city_name");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("district_name");

                    b.Property<string>("OblastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("oblast_name");

                    b.HasKey("LocationId");

                    b.HasIndex("CityName", "OblastName", "DistrictName")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_location");

                    b.ToTable("dim_location", "marketstat");
                });

            modelBuilder.Entity("MarketStat.Database.Models.MarketStat.Database.Models.Account.BenchmarkHistoryDbModel", b =>
                {
                    b.Property<long>("BenchmarkHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("benchmark_history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BenchmarkHistoryId"));

                    b.Property<string>("BenchmarkName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("benchmark_name");

                    b.Property<string>("BenchmarkResultJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("benchmark_result_json");

                    b.Property<string>("FilterCityName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filter_city_name");

                    b.Property<DateOnly?>("FilterDateEnd")
                        .HasColumnType("date")
                        .HasColumnName("filter_date_end");

                    b.Property<DateOnly?>("FilterDateStart")
                        .HasColumnType("date")
                        .HasColumnName("filter_date_start");

                    b.Property<string>("FilterDistrictName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filter_district_name");

                    b.Property<string>("FilterGranularity")
                        .HasColumnType("text")
                        .HasColumnName("filter_granularity");

                    b.Property<string>("FilterHierarchyLevelName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filter_hierarchy_level_name");

                    b.Property<int?>("FilterIndustryFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("filter_industry_field_id");

                    b.Property<string>("FilterOblastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filter_oblast_name");

                    b.Property<int?>("FilterPeriods")
                        .HasColumnType("integer")
                        .HasColumnName("filter_periods");

                    b.Property<string>("FilterStandardJobRoleTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filter_standard_job_role_title");

                    b.Property<int?>("FilterTargetPercentile")
                        .HasColumnType("integer")
                        .HasColumnName("filter_target_percentile");

                    b.Property<DateTimeOffset>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("BenchmarkHistoryId");

                    b.HasIndex("SavedAt")
                        .HasDatabaseName("idx_benchmark_history_saved_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_benchmark_history_user_id");

                    b.ToTable("benchmark_history", "marketstat");
                });

            modelBuilder.Entity("MarketStat.Database.Models.MarketStat.Database.Models.Account.UserDbModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEtlUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_etl_user");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_users_username");

                    b.ToTable("users", "marketstat");
                });

            modelBuilder.Entity("MarketStat.Database.Models.MarketStat.Database.Models.Facts.FactSalaryDbModel", b =>
                {
                    b.Property<long>("SalaryFactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("salary_fact_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SalaryFactId"));

                    b.Property<int>("DateId")
                        .HasColumnType("integer")
                        .HasColumnName("date_id");

                    b.Property<int?>("DimDateDbModelDateId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasColumnName("employer_id");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<decimal>("SalaryAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary_amount");

                    b.HasKey("SalaryFactId");

                    b.HasIndex("DateId")
                        .HasDatabaseName("idx_fact_date");

                    b.HasIndex("DimDateDbModelDateId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_fact_employee");

                    b.HasIndex("EmployerId")
                        .HasDatabaseName("idx_fact_employer");

                    b.HasIndex("JobId")
                        .HasDatabaseName("idx_fact_job");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("idx_fact_location");

                    b.ToTable("fact_salaries", "marketstat");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimEmployeeDbModel", b =>
                {
                    b.HasOne("MarketStat.Database.Models.DimEducationDbModel", "Education")
                        .WithMany()
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_dim_employee_education");

                    b.Navigation("Education");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimEmployerDbModel", b =>
                {
                    b.HasOne("MarketStat.Database.Models.DimIndustryFieldDbModel", "DimIndustryField")
                        .WithMany("DimEmployers")
                        .HasForeignKey("IndustryFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dim_employer_industry");

                    b.Navigation("DimIndustryField");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimJobDbModel", b =>
                {
                    b.HasOne("MarketStat.Database.Models.DimIndustryFieldDbModel", "IndustryField")
                        .WithMany("DimJobs")
                        .HasForeignKey("IndustryFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dim_job_industry");

                    b.Navigation("IndustryField");
                });

            modelBuilder.Entity("MarketStat.Database.Models.MarketStat.Database.Models.Account.BenchmarkHistoryDbModel", b =>
                {
                    b.HasOne("MarketStat.Database.Models.MarketStat.Database.Models.Account.UserDbModel", "User")
                        .WithMany("BenchmarkHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_benchmark_history_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketStat.Database.Models.MarketStat.Database.Models.Facts.FactSalaryDbModel", b =>
                {
                    b.HasOne("MarketStat.Database.Models.DimDateDbModel", "DimDate")
                        .WithMany()
                        .HasForeignKey("DateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fact_date");

                    b.HasOne("MarketStat.Database.Models.DimDateDbModel", null)
                        .WithMany("FactSalaries")
                        .HasForeignKey("DimDateDbModelDateId");

                    b.HasOne("MarketStat.Database.Models.DimEmployeeDbModel", "DimEmployee")
                        .WithMany("FactSalaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fact_employee");

                    b.HasOne("MarketStat.Database.Models.DimEmployerDbModel", "DimEmployer")
                        .WithMany("FactSalaries")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fact_employer");

                    b.HasOne("MarketStat.Database.Models.DimJobDbModel", "DimJob")
                        .WithMany("FactSalaries")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fact_job");

                    b.HasOne("MarketStat.Database.Models.DimLocationDbModel", "DimLocation")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fact_location");

                    b.Navigation("DimDate");

                    b.Navigation("DimEmployee");

                    b.Navigation("DimEmployer");

                    b.Navigation("DimJob");

                    b.Navigation("DimLocation");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimDateDbModel", b =>
                {
                    b.Navigation("FactSalaries");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimEmployeeDbModel", b =>
                {
                    b.Navigation("FactSalaries");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimEmployerDbModel", b =>
                {
                    b.Navigation("FactSalaries");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimIndustryFieldDbModel", b =>
                {
                    b.Navigation("DimEmployers");

                    b.Navigation("DimJobs");
                });

            modelBuilder.Entity("MarketStat.Database.Models.DimJobDbModel", b =>
                {
                    b.Navigation("FactSalaries");
                });

            modelBuilder.Entity("MarketStat.Database.Models.MarketStat.Database.Models.Account.UserDbModel", b =>
                {
                    b.Navigation("BenchmarkHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
