FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

ARG PROJECT_NAME

COPY published/${PROJECT_NAME}/ .

ENV DLL_NAME="${PROJECT_NAME}.dll"

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT ["sh", "-c", "exec dotnet ${DLL_NAME}"]